#+begin_header
#+TITLE: Sampling Orientational Space of Organic Structure Directing Agents in Zeolites: Genetic Algorithm vs. Classical Mechanics
  
#+LATEX_CLASS: achemso
#+LATEX_CLASS_OPTIONS: [journal=accacs,manuscript=article, email=true, layout=traditional]
#+EXPORT_EXCLUDE_TAGS: noexport
#+OPTIONS: author:nil date:nil toc:nil ':t
#+latex_header: \setkeys{acs}{biblabel=brackets,super=true,articletitle=False,maxauthors=0}
#+latex_header: \usepackage[utf8]{inputenc}
#+latex_header: \usepackage[T1]{fontenc}
#+latex_header: \usepackage{fixltx2e}
#+latex_header: \usepackage{url}
#+latex_header: \usepackage{siunitx}
#+latex_header: \usepackage{mhchem}
#+latex_header: \usepackage{graphicx}
#+latex_header: \usepackage{color}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{textcomp}
#+latex_header: \usepackage{wasysym}
#+latex_header: \usepackage{latexsym}
#+latex_header: \usepackage{amssymb}
#+latex_header: \usepackage{minted}
#+latex_header: \usepackage[section]{placeins}
#+latex_header: \usepackage[linktocpage, pdfstartview=FitH, colorlinks=true, linkcolor=blue, anchorcolor=blue, citecolor=blue, filecolor=blue, menucolor=blue, urlcolor=blue]{hyperref}
#+latex_header: \usepackage{attachfile}
#+latex_header: \newcommand{\red}[1]{\textcolor{red}{#1}}
#+latex_header: \newcommand{\blue}[1]{\textcolor{blue}{#1}}
#+latex_header: \keywords{}
#+latex_header:\renewcommand{\thefigure}{\arabic{figure}}
#+latex_header:\renewcommand{\thetable}{\arabic{table}}
#+latex_header:\usepackage{lmodern}
#+latex_header:\usepackage{cleveref}

#+latex_header: \author{Craig Waitt}
#+latex_header: \affiliation{Department of Chemistry and Biochemistry, University of Notre Dame, Notre Dame, Indiana 46556, United States}

#+latex_header: \author{Xuyao Gao}
#+latex_header: \affiliation{Department of Chemical and Biomolecular Engineering, University of Notre Dame, Notre Dame, Indiana 4656, United States}

#+latex_header: \author{William F. Schneider}
#+latex_header: \email{wschneider@nd.edu}
#+latex_header: \affiliation{Department of Chemical and Biomolecular Engineering, University of Notre Dame, Notre Dame, Indiana 46556, United States}
#+latex_header: \alsoaffiliation{Department of Chemistry and Biochemistry, University of Notre Dame, Notre Dame, Indiana 46556, United States}

#+end_header

\newpage

* Workflow

** Objectives

1. Develop models to capture/describe the orientational preference a framework (FW) has for a particular organic structure directing agent (OSDA)
   1. Compare Genetic Algorithm (GA) and Classical Molecular Dynamics (CMD) ability to sample global configurational space
   2. Compare GA and CMD ability to sample local configuration
   3. Compare Drieding force field with DFT

** Plan of Attack

1. \textbf{What is the preferential orientational of a specific OSDA/Zeolite combination}

   1. Develop a model to capture OSDA Orientations
      * Classical molecular dynamics (CMD) at very high temperatures ($T \geq 5,000$) to sample different possible orientation

   2. Compute interaction energy (IE) of all FW and OSDA combinations (maybe free energies):
      * CHA and AEI with TMADA, DMDMP (isomers), and DEDMP (isomers)
	+ include LTA and TMA? 
      * Using CMD at \SI{343}{K} (rigid framework)
      * Using density functional theory with dispersion (DFT-D3) (flexible framework)
	+ Rigid Framework as well?

   3. Evaluate orientation and positioning dependence of OSDA in FW
      * Measure the orientation of an OSDA relative to some axis which encompases the cage the OSDA is in
      * Measure the location of the OSDA center of mass is relative to the center of the zeolite cage

2. \textbf{What limitations does each model posses?}

   1. GA-DFT is time restrictive compared to CMD. GA allows for ease of global sampling of OSDA in a cage. Framework can be rigid or flexible. Local configuration is relatively fixed (DEDMP for example).

   2. CMD is quick. Can sample larger ranges of global configurations. Requires sampling at very high temperatures (5000 K) and resampling at normal temperatures (more steps that GA). Currently can do multiple OSDA's (possible in GA but parents must be made by hand). Framework must be rigid (Drieding). CMD allows OSDA to sample local configurations. 

   3. Combined GA-CMD-DFT. GA to sample Global configurations. CMD to sample local configurations. DFT to relax FW and get Energy (IE).

3. \textbf{Combined GA-CMD-DFT}

   1. Use GA to sample Global configuration.

   2. Identify "unique" orientations/configurations

   3. Use CMD to sample local configurations of "unique" orientations/configurations

   4. Identify "unique" subset of each orientation/configuration

   5. Re-optimize with DFT (or electronic structure) if desired






* Results to Date
** GA vs CMD (Structures and Energetics)
Using the parameters discussed above, we will first compare the lowest energy structure using GA and CMD. The table below describes which method provide similar structures. 

\begin{center}
\begin{tabular}{c c c| c c c  }
 \hline
          & CHA &  & & AEI &\\ 
 \hline
 OSDA     & DFT & CMD &  & DFT & CMD \\
 \hline
 TMADA    & Yes & Yes &  & Yes & Yes \\ 
 DMDMP-2c & Yes & Yes &  & Yes & Yes \\  
 DMDMP-3c & Yes & Yes &  & Difference in Glob Min & See Notes\\
 DMDMP-3t & Done & Running &  & Difference in Glob Min & See Notes \\
 DEDMP-2c & Done & Running &  & Difference in Glob Min & Exo/Endo Orient \\
 DEDMP-3c & Done & Running &  & Difference in Glob Min & Exo/Endo Orient \\
 DEDMP-3t & Done & Running &  & Done & Running \\ 
 \hline
\end{tabular}
\end{center}
